# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 051e1e7ce479859dfca42ca1ce2b9da242c48bff19ab6dedd3de5ffec9ee58680464d184d558bd3ceda8f42552468a9fd939377bda1eab4962eefab2cc67c92a

test:
  secret_key_base: 7cf16f70d1a045d54664fc0bcafd646b5eab00e4dcd27cf8161af30a06f1a17b20f7015b33fe9d25480197a7f9a08e093dfa01f895134a4f0783a2c78555a350

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
